### ISSUE TITLE
Doesn't deploy github app

### ISSUE THREAD

**Issue by semenko** [gcollazo/Fabulous#3]
Perhaps I'm missing something, but it looks like GITHUB_REPO is never referenced, and no github app is ever deployed.

**Comment by gcollazo** [comment]
You are right. The app is no being deployed, instead we are creating an empty django app where the app should go. This feature will be added very soon. I'm trying to figure out a way to accomodate for all the different app setups out there and It's kind of a challenge. I think an option might be to assume people are using south for migrations but this might be wrong for many cases. The other option is to just clone the app and let the user manage the DB sync and migration. In any case the goal is to make the process as automated as possible with the least amount of effort for the developer using Fabulous.

Any suggestions are hugely appreciated.

In the meantime what you can do is ssh into the server and clone your app into the ~/webapps/APPNAME folder and then deal with db sync and migration.

**Comment by yuvadm** [comment]
This issue should **definitely** be mentioned upfront in the README.
